// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlWNrTLapV4mVB1m0Nvx3-Urt1QYzdD9w',
    appId: '1:146944593967:web:d4f7a2d78e5ec903c136da',
    messagingSenderId: '146944593967',
    projectId: 'chat-app-2c620',
    authDomain: 'chat-app-2c620.firebaseapp.com',
    storageBucket: 'chat-app-2c620.appspot.com',
    measurementId: 'G-0CMB10MPYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfMkMPY7cHD6SdbuiuyOGU8g25T5VrnVM',
    appId: '1:146944593967:android:923af00f109cd5e2c136da',
    messagingSenderId: '146944593967',
    projectId: 'chat-app-2c620',
    storageBucket: 'chat-app-2c620.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCP8J0zkDt4DN24NT6cYpxh8LWFqWW7oI',
    appId: '1:146944593967:ios:54cde362d1f2d504c136da',
    messagingSenderId: '146944593967',
    projectId: 'chat-app-2c620',
    storageBucket: 'chat-app-2c620.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCP8J0zkDt4DN24NT6cYpxh8LWFqWW7oI',
    appId: '1:146944593967:ios:54cde362d1f2d504c136da',
    messagingSenderId: '146944593967',
    projectId: 'chat-app-2c620',
    storageBucket: 'chat-app-2c620.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlWNrTLapV4mVB1m0Nvx3-Urt1QYzdD9w',
    appId: '1:146944593967:web:3e1199dcb7755b6ec136da',
    messagingSenderId: '146944593967',
    projectId: 'chat-app-2c620',
    authDomain: 'chat-app-2c620.firebaseapp.com',
    storageBucket: 'chat-app-2c620.appspot.com',
    measurementId: 'G-KXRTYB1WHR',
  );
}
